defaults:
  - blank_ratio: 10-90
  - dataset: config
  - model: attention
  - settings: config
  - _self_

hydra:
  job:
    chdir: true
  sweep:
    subdir: ${hydra.job.override_dirname}

seed: 0
use_cuda: true
tmp: 10-90